# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Johan Linåker's homepage
email: johan [dot] linaker [at] ri [dot] se
description: >- # this means to ignore newlines until "baseurl:"
  Johan Linåker is a Senior Researcher at RISE Research Institutes of Sweden. His research interests include empirical software engineering in the context of open technologies. Open technologies refer to technology-related artifacts that is shared, reused and collaboratively developed between its users and stakeholders. Here, Johan is specifically interested in how actors in public and private sector can use, develop, and collaborate on Open Source Software, Open and shared data, and Open Standards to enable and promote interoperability, technological independence, and open innovation.
twitter_username: johanlinaker
github_username: johanlinaker
minimal_mistakes_skin: default
search: false
url: 'https://johanlinaker.github.io/' # your main domain
baseurl: '' # if you're using custom domain keep this blank example: baseurl: ''

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Johan Linåker"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Senior Researcher at <a href=\"https://www.ri.se/en/person/johan-linaker\">RISE Research Institutes of Sweden</a>"
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/johanlinaker"
    - label: "Mastodon"
      icon: "fab fa-mastodon"
      url: "https://mastodon.se/@johanlinaker"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/johanlinaker"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/johanlinaker/"
    - label: "Google Scholar"
      icon: "ai ai-google-scholar fa-lg"
      url: "https://scholar.google.com/citations?user=InMNgF0AAAAJ&hl=sv&oi=ao"
    - label: "Orcid"
      icon: "ai ai-orcid"
      url: "https://orcid.org/0000-0001-9851-1404"

footer:

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
